# Generated by Django 4.2.4 on 2023-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
                ('song_album', models.CharField(max_length=100)),
                ('song_genre', models.CharField(max_length=100)),
                ('song_year', models.IntegerField()),
            ],
        ),
    ]
