# Generated by Django 4.2.4 on 2023-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_tag_rename_song_album_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='scheduled_publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
