# Generated by Django 4.2.4 on 2023-08-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
